stages:
  - build
  - deploy

build-image:
  stage: build
  before_script:
    - docker compose --env-file /home/admin/adameds/.env-igd down --rmi all
  script:
    - docker build -t adameds/igd-service:dev ./ --no-cache
  only:
    - main

deploy-app:
  stage: deploy
  only:
    - main
  script:
    - docker compose --env-file /home/admin/adameds/.env-igd up -d