version: '3.3'
services:
  adameds-igd:
    image: adameds/igd-service:dev
    container_name: adameds-igd
    ports:
      - ${APPLICATION_PORT}:8084
    restart: always
    networks:
      - igd-network
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DIALECT=${DB_DIALECT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
networks:
  igd-network:
    driver: bridge