services:
  adameds-igd:
    build: 
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    image: adameds/igd-service:dev
    container_name: adameds-igd
    ports:
      - ${APPLICATION_PORT}:8084
    restart: always
    networks:
      - igd-network
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DIALECT=${DB_DIALECT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - type: bind
        source: /home/admin/adameds/private.key
        target: /adameds-igd/private.key
      - type: bind
        source: /home/admin/adameds/public.key
        target: /adameds-igd/public.key
      - type: bind
        source: /home/admin/adameds/.env.vault
        target: /adameds-igd/.env.vault
networks:
  igd-network:
    driver: bridge